"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DateFormatEnum = {};
exports.DateFormatEnum.YEAR = 1;
exports.DateFormatEnum.MONTH = 2;
exports.DateFormatEnum.DAY = 3;
exports.DateFormatEnum.HOUR = 4;
exports.DateFormatEnum.MINUTE = 5;
exports.DateFormatEnum.SECOND = 6;
exports.DateFormatEnum[exports.DateFormatEnum.YEAR] = "YEAR";
exports.DateFormatEnum[exports.DateFormatEnum.MONTH] = "MONTH";
exports.DateFormatEnum[exports.DateFormatEnum.DAY] = "DAY";
exports.DateFormatEnum[exports.DateFormatEnum.HOUR] = "HOUR";
exports.DateFormatEnum[exports.DateFormatEnum.MINUTE] = "MINUTE";
exports.DateFormatEnum[exports.DateFormatEnum.SECOND] = "SECOND";
;
