export let DateFormatEnum = {};
DateFormatEnum.YEAR = 1;
DateFormatEnum.MONTH = 2;
DateFormatEnum.DAY = 3;
DateFormatEnum.HOUR = 4;
DateFormatEnum.MINUTE = 5;
DateFormatEnum.SECOND = 6;
DateFormatEnum[DateFormatEnum.YEAR] = "YEAR";
DateFormatEnum[DateFormatEnum.MONTH] = "MONTH";
DateFormatEnum[DateFormatEnum.DAY] = "DAY";
DateFormatEnum[DateFormatEnum.HOUR] = "HOUR";
DateFormatEnum[DateFormatEnum.MINUTE] = "MINUTE";
DateFormatEnum[DateFormatEnum.SECOND] = "SECOND";
;
